[tool.poetry]
name = "bot-of-grond"
version = "0.1.0"
description = ""
authors = ["anrde <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
praw = "^7.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
